# Generated by Django 5.0.7 on 2024-08-08 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_alter_profile_full_name_alter_profile_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_pattern', models.CharField(max_length=255, unique=True)),
                ('svg_data', models.TextField()),
            ],
        ),
    ]
