# Generated by Django 5.0.7 on 2024-08-08 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_socialmediaicon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmediaicon',
            name='svg_data',
        ),
        migrations.AddField(
            model_name='socialmediaicon',
            name='svg',
            field=models.FileField(blank=True, null=True, upload_to='svgs/'),
        ),
    ]
