# Generated by Django 5.0.7 on 2024-08-21 12:11

import django.core.validators
import userapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_remove_socialmediaicon_svg_data_socialmediaicon_svg'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/', validators=[django.core.validators.FileExtensionValidator(['pdf']), userapp.models.validate_pdf_size]),
        ),
    ]
